### ISSUE TITLE
Multiple fields per pinpoint / design tweaks?

### ISSUE THREAD

**Issue by duncanmcclean** [FrameworkDesign/pinpoint-image#2] opened 2022-08-08 12:45 UTC
Hey - thanks so much for this! It's a great starting point for implementing this into a new project of ours.

I've managed to get it up and running and think I have a good grasp of how much work it would take us to integrate... there's a couple of things that we'd need which don't seem to be supported (currently). 

### Question: Multiple text fields

After looking at our designs for this project, it looks like each of the "pin points" has both a heading and another bit of text. 

![image](https://user-images.githubusercontent.com/19637309/183420276-86a6aaa1-87f2-4932-808e-19a8edd18764.png)

This probably isn't something everybody would need but just trying to plan out how we'd build these... any ideas?

### Suggestion: Design tweaks

I've already published the Blade view for the addon so we can add our own custom "pins" and customise the styling etc.

However, in the Control Panel, I noticed there could possibly be a few tweaks to the fieldtype to make it a little more _friendly_ (for lack of a better word).

I made a little mockup of some tweaks I thought of on the spot. Dunno if you'd be up for them - happy to PR them into this addon when I have the time?

![image](https://user-images.githubusercontent.com/19637309/183419363-8c0fdfa7-f026-428d-9da0-f292ce5b7249.png)

---

Apologies if this sounds like me moaning or comes off in a negative way. This addon gets us 80% of the way there, we just need to figure out these two things - if they can both be done in the addon itself, that would be great, to avoid us maintaining a fork.

**Comment by wm-simon** [comment] 2022-08-08 14:45
Hey Duncan, if I understand your preview right, you want to make the pinpoints field wider and shrink the image. I my case I work with large images (website-screens) and it is already hard to get the right point with the mouse (see image). I think a good solution would be a modal box or something like that, where you can edit the content form the pinpoint. But I have no idea how much work it is, to make something like this working. 

![image](https://user-images.githubusercontent.com/3351449/183444518-afa7170a-9b42-459e-8747-70a634b274f8.png)

**Comment by duncanmcclean** [comment] 2022-08-08 15:08
Yeah, that makes sense. I don't have a bunch of time to spend on it but could look into making a modal for the 'pinpoint selection' stuff to give more room.

Any ideas on the 'multiple fields' question?

**Comment by paulweareframework** [comment] 2022-08-15 15:37
thank you so much for the kind feedback and really appreciate how friendly and structured it is.

@duncanmcclean you are in no way being moany or coming across as such.
Your feedback is very helpful and very good and feeds into what we are planning next to do and similar to feedback on https://github.com/FrameworkDesign/pinpoint-image/issues/1

You guys are absolutely spot on and very helpful with guiding it to a much better version that helps you all use.


So with the next update I plan to utilise a modal or slide out for the editing of a points content.
Effectively this would mean the left column could become much much slimmer and we would utilise icons and tooltips for each icon.



We also plan to bring in these change, which are referenced in https://github.com/FrameworkDesign/pinpoint-image/issues/5:

- change the order from the pinpoints (via drag & drop)
- move the pinpoints position (via drag & drop)


Now for multiple fields, I was going to try and wrap that up into the modal, as in for now start with a heading but then integrate a repeater that will allow you to add multiple fields per row in the popup/slide out

does that sound good to you both @duncanmcclean & @wm-simon?


Apologies for any delays or if this has held you up. 
I will be on this tomorrow and wednesday evening.

**Comment by duncanmcclean** [comment] 2022-08-15 16:27
Yes, that sounds good!

**Comment by wm-simon** [comment] 2022-08-15 21:03
Sounds perfect, thanks!

**Comment by paulweareframework** [comment] 2022-08-18 17:08
Hey Guys, 

sorry for the extra day its taken!
I've just tagged v0.0.7 and this now has:
- change the order from the pinpoints (via drag & drop)
- move the pinpoints position (via drag & drop)
- Modal for field content
- multiple fields in modal content
- - markdown, textarea & text so far
- updated template tag with example of how to output the new fields

If you guys could give it a try and let me know if its good for you :)

**Comment by duncanmcclean** [comment] 2022-08-18 20:11
Thanks! I'll try and take a look tomorrow/next week! I appreciate the work that's gone into the changes 😄

**Comment by wm-simon** [comment] 2022-08-19 20:33
Great step, thanks for your work! 

The design looks a little bit buggy, i think. This could be caused by the large images.
![image](https://user-images.githubusercontent.com/3351449/185701448-bfb6f458-c92c-481d-85c3-7600c352a565.png)
Here a link to the image:
[![screencapture-reimann-holzbau-online-de-2022-07-15-13_30_54](https://i.im.ge/2022/08/20/ODUjmz.screencapture-reimann-holzbau-online-de-2022-07-15-13-30-54.md.png)](https://im.ge/i/ODUjmz)

I can not move the points with drag/drop as well. I'm on the latest Chrome.

**Comment by paulweareframework** [comment] 2022-08-20 16:04
@wm-simon 
I think this is a caching issue.
I downloaded your image and its working.
So I think this is more a lesson for me to deploy updates and ensure the cache clears.

for now to fix it could you do this:
- if on mac cmd + shift + R
- if on windows I can't remember sorry!

**Comment by paulweareframework** [comment] 2022-09-07 13:44
Am I ok to close this now?

**Comment by wm-simon** [comment] 2022-09-09 15:21
Hey, sorry for the delay, I was really busy.

I've tested all again, cleared the cache, tried it in incognito modus and installed the addon again. 

The issues are still there. Here a video:
https://somup.com/c3QQoqUtjj

**Comment by paulweareframework** [comment] 2022-09-09 15:39
> Hey, sorry for the delay, I was really busy.
> 
> I've tested all again, cleared the cache, tried it in incognito modus and installed the addon again.
> 
> The issues are still there. Here a video: https://somup.com/c3QQoqUtjj

Oh no thats not good!

What version of statamic and php version is this on?
What browser too?

Hopefully I can recreate the setup to recreate the bug and then get a fix right away to you

**Comment by wm-simon** [comment] 2022-09-09 18:23
Windows 10
Laravel Version: 9.27.0
PHP Version: 8.0.12
Chrome: Chrome 105 (latest)

Hope, this helps.

**Comment by paulweareframework** [comment] 2022-09-12 08:43
I am really struggling to recreate.
Is there anyway I could get a copy of the site or access to the repository?
I really wish to find out what it is so can fix it for you and in case anyone else ever encounters this issue

**Closed as completed** 2022-10-06 08:16 UTC
Labels: enhancement, feature
